services:

  esense:
    image: emosense
    hostname: emosense
    container_name: emosense
    ports:
        - '8000:8000'
    environment:
        - MODEL_PATH=/temp/models/model.h5
        - CONFIG_PATH=/temp/config/config.json
        - IMAGE_INPUT_DIR=/temp/images
        - JSON_OUTPUT_DIR=/temp/json

    volumes:
      - /Users/fafa/temp:/temp
