services:

  esense:
    image: emosense
    hostname: emosense
    container_name: emosense
    ports:
        - '8000:8000'
    environment:
        - MODEL_PATH=/emosense/models/model.h5
        - CONFIG_PATH=/emosense/config.json
        - IMAGE_INPUT_DIR=/emosense/images
        - JSON_OUTPUT_DIR=/emosense/json

    volumes:
      - /Users/fafa/temp:/emosense/
